# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Eerie Space
email: the.eerie.space@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  All about solo TTRPGs, now playin Seekers Beyond The Shroud, Mothership RPG,
     Old School Essentials, Labyrinth Lord and a Rasp of Sand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eeriespace.github.io" # the base hostname & protocol for your site
twitter_username: mazmorreo 
#github_username:  eeriespace 

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-159094225-1
disqus_shortname: eeriespace

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
